name: valkyrie_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  another_flushbar: ^1.10.24
  bloc: ^7.2.0
  calendar_time: ^2.0.0
  cyclop: ^0.4.1
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_hooks: ^0.18.0
  flutter_typeahead: ^3.2.1
  freezed_annotation: ^0.14.3
  get_it: ^7.2.0
  hive: ^2.0.4
  http_parser: ^4.0.0
  image_cropper: ^1.4.1
  image_downloader: ^0.30.0
  image_picker: ^0.8.4+2
  injectable: ^1.5.0
  intl: ^0.17.0
  path_provider: ^2.0.5
  photo_view: ^0.12.0
  transparent_image: ^2.0.0
  web_socket_channel: ^2.1.0
  webview_flutter: ^2.0.14

dev_dependencies:
  build_runner: ^2.1.2
  built_value: ^8.1.2
  flutter_launcher_icons: '^0.9.2'
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  hive_generator: ^1.1.1
  injectable_generator: ^1.5.2
  lint: ^1.7.2

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/icon.png'

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_native_splash:
  color: '#35383E'
  image: assets/logo.png
