name: Analyze and Test

on:
  pull_request:
  push:

jobs:
  lint:
    name: Analyze the code
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with 2.5.1 version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.1'
          channel: 'stable'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

  test:
    name: Test on ubuntu-latest
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Clone flutter repository from stable channel with 2.5.1 version
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.5.1'
          channel: 'stable'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update dependencies
        run: flutter pub get

      - name: Test
        run: flutter test
